# Generated by Django 4.2.5 on 2023-09-14 23:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('contact', models.CharField(max_length=15)),
                ('address', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=50)),
                ('state', models.CharField(max_length=50)),
                ('zipcode', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Technician',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('technician_name', models.CharField(max_length=50)),
                ('technician_surname', models.CharField(max_length=50)),
                ('technician_email', models.EmailField(max_length=254)),
                ('technician_phone', models.CharField(max_length=15)),
                ('technician_company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Ticket_App.company')),
            ],
        ),
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('ticket_title', models.CharField(max_length=50)),
                ('ticket_description', models.CharField(max_length=100)),
                ('ticket_status', models.CharField(max_length=50)),
                ('ticket_priority', models.CharField(max_length=50)),
                ('ticket_service', models.CharField(max_length=50)),
                ('ticket_company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Ticket_App.company')),
                ('ticket_technician', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Ticket_App.technician')),
            ],
        ),
        migrations.AddField(
            model_name='technician',
            name='technician_ticket',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Ticket_App.ticket'),
        ),
        migrations.CreateModel(
            name='Dispatcher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dispatcher_name', models.CharField(max_length=50)),
                ('dispatcher_surname', models.CharField(max_length=50)),
                ('dispatcher_email', models.EmailField(max_length=254)),
                ('dispatcher_phone', models.CharField(max_length=15)),
                ('dispatcher_company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Ticket_App.company')),
            ],
        ),
    ]
