# Generated by Django 4.2.5 on 2023-09-16 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ticket_App', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='company_address',
            field=models.CharField(default='No Address Provided', max_length=100),
        ),
        migrations.AddField(
            model_name='company',
            name='company_city',
            field=models.CharField(default='No City Provided', max_length=100),
        ),
        migrations.AddField(
            model_name='company',
            name='company_email',
            field=models.EmailField(default='No Email Provided', max_length=100),
        ),
        migrations.AddField(
            model_name='company',
            name='company_phone',
            field=models.CharField(default='No Email Provided', max_length=13),
        ),
        migrations.AddField(
            model_name='company',
            name='company_state',
            field=models.CharField(default='No State Provided', max_length=100),
        ),
        migrations.AddField(
            model_name='company',
            name='company_zip',
            field=models.CharField(default='No ZipCode Provided', max_length=5),
        ),
        migrations.AlterField(
            model_name='company',
            name='company_name',
            field=models.CharField(default='No Name Provided', max_length=100),
        ),
    ]
