# Generated by Django 4.2.5 on 2023-09-30 03:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ticket_App', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='tech_comment',
            field=models.TextField(max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('accepted', 'Accepted'), ('monitored', 'Monitored'), ('rejected', 'Rejected'), ('closed', 'Closed')], default='pending', max_length=100),
        ),
    ]
