# Generated by Django 4.2.5 on 2023-09-20 00:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Ticket_App', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='dispatcher',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='dispatcher_tickets', to='Ticket_App.systemuser'),
        ),
        migrations.AddField(
            model_name='ticket',
            name='technician',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='technician_tickets', to='Ticket_App.systemuser'),
        ),
    ]
