# Generated by Django 4.2.5 on 2023-09-30 04:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Ticket_App', '0002_ticket_tech_comment_alter_ticket_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ticket',
            name='tech_comment',
        ),
    ]
