# Generated by Django 4.2.5 on 2023-09-20 01:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ticket_App', '0002_ticket_dispatcher_ticket_technician'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedback',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('not_posted', 'Not Posted'), ('posted', 'Posted')], default='pending', max_length=100),
        ),
    ]
