# Generated by Django 4.2.5 on 2023-09-20 21:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ticket_App', '0003_feedback_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedback',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
