# Generated by Django 4.2.5 on 2023-10-04 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ticket_App', '0003_remove_ticket_tech_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedback',
            name='status',
            field=models.CharField(choices=[('not_posted', 'Not Posted'), ('posted', 'Posted')], default='not_posted', max_length=100),
        ),
    ]
