# Generated by Django 4.2.5 on 2023-09-20 22:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Ticket_App', '0004_feedback_email'),
    ]

    operations = [
        migrations.RenameField(
            model_name='feedback',
            old_name='title',
            new_name='name',
        ),
    ]
