# Generated by Django 4.2.5 on 2023-09-21 00:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ticket_App', '0005_rename_title_feedback_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='is_company',
            field=models.BooleanField(default=True),
        ),
    ]
